name: Build and Push Apps

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: kromplon-admin
            dockerfile: Dockerfile
            tag: kromplon-admin

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase repo variables
        id: vars
        run: |
          echo "REPO_OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ matrix.service.tag }}:latest
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ matrix.service.tag }}:${{ github.sha }}

  deploy:
    name: Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase repo variables
        id: vars
        run: |
          echo "REPO_OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Deploy and restart Docker container via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ env.REPO_OWNER_LOWER }}/kromplon-admin:latest
            docker stop kromplon-admin || true
            docker rm kromplon-admin || true
            docker run -d --name kromplon-admin -p 8000:80 ghcr.io/${{ env.REPO_OWNER_LOWER }}/kromplon-admin:latest